### ISSUE TITLE
Microsoft.ML.OnnxRuntimeGenAI.OnnxRuntimeGenAIException: The driver's state is probably suspect

### ISSUE THREAD

**Issue by s7023369667** [microsoft/Phi3-Chat-WinUI3-Sample#2]
Hi, I try to run the sample of this.
I believe that the "dml" in provider_options would use the GPU to compute.
However, I get this error while entry the prompt:
`Microsoft.ML.OnnxRuntimeGenAI.OnnxRuntimeGenAIException:  887A0020 An internal issue prevented the driver from carrying out the specified operation. The driver's state is probably suspect`

By the way, I have testified that without the "dml" in  provider_options, everything work fine and super slow.

Other question:
How do I choose to run the computation on my NPU?

Environment:
Windows 11 Pro 24H2
CPU: Snapdragon(R) X Elite - X1E78100 - Qualcomm(R) Oryon(TM) CPU   3.42 GHz
GPU: Snapdragon(R) X Elite - X1E78100 - Qualcomm(R) Adreno(TM) GPU
NPU: Snapdragon(R) X Elite - X1E78100 - Qualcomm(R) Hexagon(TM) NPU

I am wondering that the model of phi-3 is currently not support for Qualcomm GPU and NPU 
Thanks for any help! :D

**Comment by azchohfi** [comment]
I don't believe NPU is supported just yet.
I would suggest asking this question at the OnnxRuntimeGenAI repo:
https://github.com/microsoft/onnxruntime-genai
